### ISSUE TITLE
Update Newtonsoft.Json to 13.0.1

### ISSUE THREAD

**Issue by jasonycw** [danielwertheim/jsonnet-contractresolvers#1]
There are some new nullable changes there which may cause some nullable syntax errors.

When some other libraries use `Newtonsoft.Json` 13+ seems will have mismatch error
```
Unhandled exception. System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load file or assembly 'Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
Could not load file or assembly 'Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at MediatR.Registration.ServiceRegistrar.<>c.<ConnectImplementationsToTypesClosing>b__1_0(Assembly a)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at MediatR.Registration.ServiceRegistrar.ConnectImplementationsToTypesClosing(Type openRequestInterface, IServiceCollection services, IEnumerable`1 assembliesToScan, Boolean addIfAlreadyExists)
   at MediatR.Registration.ServiceRegistrar.AddMediatRClasses(IServiceCollection services, IEnumerable`1 assembliesToScan)
   at MediatR.ServiceCollectionExtensions.AddMediatR(IServiceCollection services, IEnumerable`1 assemblies, Action`1 configuration)
   at MediatR.ServiceCollectionExtensions.AddMediatR(IServiceCollection services, Assembly[] assemblies)
```

Temporary fix for me is for every projects that uses this library, also add reference to `Newtonsoft.Json` 13+ explicitly.

**Comment by danielwertheim** [comment]
There's now a v2.0.0 out that targets v13.0.1 (might take a while before NuGet has indexed it).
